# config.example.yaml
app:
  port: ":8080"
  env: "development"
database:
  host: "localhost"
  user: "user"
  password: "your-password-here"
  name: "membership"
  port: "5432"
jwt:
  secret: "your-jwt-secret"
